import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		int	totalBodyCount = 0,
			famsOf2 = 0,
			famsOf3 = 0,
			famsOf4More = 0;
		
		for(int i=0; i < T; i++) {
			boolean gotBoy = false,
				gotGirl = false;
				
			int bodyCount = 0;
		
			while (!gotBoy || !gotGirl) {
				if (generator.nextDouble() < 0.5) {
					gotGirl = true;
					//System.out.print("g ");
				}
				else {
					gotBoy = true;
					//System.out.print("b ");
				}
			
				bodyCount++;
				totalBodyCount++;
			}
		
			//System.out.println("\nYou made it... and now you have " + bodyCount + " children.");
			if (bodyCount == 2)	famsOf2++;
			else if (bodyCount == 3) famsOf3++;
			else famsOf4More++;
			}
			
			double avg = (double) totalBodyCount / T;
			System.out.println("Average: " + avg + " children to get at least one of each gender.");
			System.out.println("Number of families with 2 children: " + famsOf2);
			System.out.println("Number of families with 3 children: " + famsOf3);
			System.out.println("Number of families with 4 or more children: " + famsOf4More);
			
			if (famsOf2 >= Math.max(famsOf3, famsOf4More)) {
				System.out.println("The most common number of children is 2.");
			} else {
				if (famsOf3 >= famsOf4More) {
					System.out.println("The most common number of children is 3.");
				} else {
					System.out.println("The most common number of children is 4 or more.");
				}
			}
		    
	}
}
